#include <iostream>
#include <vector> // for for loop

void autoKeyword();
void forLoop();
void lambdaExpression();

int main() {
    autoKeyword();
    forLoop();
    lambdaExpression();
    return 0;
}

void autoKeyword() {
    auto message = "Hello World";  // uses auto keyword to automatically deduce type of var
    std::cout << message << std::endl;
}

void forLoop() {
    std::vector /* a container that holds a sequence of elements that can grow/shrink */ <std::string> /* type of elements the vector holds */ messages = {"Hello", "World"};
    for (const /* prevent changing the element inside the loop */ auto& /* automatically deduce type. "&" makes it a reference to each element
        (refers to an object, does not copy it (an "alias"); very fast. allows modification if not const.)*/ word : messages) {
        std::cout << word << " "; // prints current word and adds a space
    }
    std::cout << std::endl; // move to the next line
}

void lambdaExpression() {
    auto printMessage /* variable type is unique for lambda; unnamed and generated by compiler */ = /* creates a variable from the stuff on the right (temporary object from lambda) */ []() {
        // brackets are a capture list which captures external variables. the {} is a parameter list for arguments like a normal function
        std::cout << "Hello World" << std::endl;
    }; // note semicolon after closing brace; ends variable definition
    printMessage(); // calls the lambda like a function
}
